# ===================================================================
# Spring Boot configuration for the "dev" profile.
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    me.duvu.esoftorder: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3308/esoftOrder?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  liquibase:
    contexts: dev

  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard

server:
  port: 8081