# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  esoftorder-app:
    image: esoftorder
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://esoftorder-mysql:3308/esoftorder?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://esoftorder-mysql:3308/esoftorder?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - APP_SLEEP=5 # gives time for other services to boot before the application
  esoftorder-mysql:
    image: mysql:8.0.28
    cap_add:
      - SYS_NICE
    # volumes:
    #   - ~/volumes/esoftOrder/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=esoftorder
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:3308:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
